FROM fedora:latest


LABEL ios.k8s.display-name="fossul-server" \
    maintainer="Keith Tenzer <ktenzer@redhat.com>"

RUN mkdir /app && \
    mkdir /app/plugins

RUN groupadd -r fossul &&\
    useradd -r -g fossul -d /app -u 1001 -s /sbin/nologin -c "Fossul user" fossul

ENV HOME=/app

RUN curl -L https://github.com/fossul/fossul/releases/download/latest/storage-service.tar.gz |tar xz;mv storage /app;mv fossul-storage-startup.sh /app && \
    curl -L https://github.com/fossul/fossul/releases/download/latest/plugins-storage.tar.gz |tar xz;mv storage/ /app/plugins && \
    curl -L https://github.com/fossul/fossul/releases/download/latest/plugins-archive.tar.gz |tar xz;mv archive/ /app/plugins   

RUN chown -R fossul:fossul /app && \
    chmod -R 775 /app && \
    chmod -R 777 /tmp

RUN echo "1.0" > /etc/imageversion

USER fossul

WORKDIR /app

CMD /app/fossul-storage-startup.sh