FROM registry.redhat.io/ubi8/ubi:latest


LABEL ios.k8s.display-name="fossul-server" \
    maintainer="Keith Tenzer <ktenzer@redhat.com>"

RUN mkdir /app && \
    mkdir /app/plugins

RUN groupadd -r fossul &&\
    useradd -r -g fossul -d /app -u 1001 -s /sbin/nologin -c "Fossul user" fossul

ENV GOBIN=/app
ENV HOME=/app

RUN curl -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz |tar xz;mv openshift*/oc /app;mv openshift*/kubectl /app && \
    curl -L https://github.com/fossul/fossul/releases/download/latest/storage-service.tar.gz |tar xz -C /app && \
    ls -l /app && \
    curl -L https://github.com/fossul/fossul/releases/download/latest/plugins-storage.tar.gz |tar xz -C /app/plugins && \
    ls -l /app/plugins/storage &&\
    curl -L https://github.com/fossul/fossul/releases/download/latest/plugins-archive.tar.gz |tar xz -C /app/plugins && \   
    ls -l /app/plugins/archive

RUN chown -R fossul:fossul /app && \
    chmod -R 775 /app && \
    chmod -R 777 /tmp

RUN echo "1.0" > /etc/imageversion

USER fossul

WORKDIR /app

CMD /app/fossul-storage-startup.sh