---
- name: Deploy Fossul without Operator
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    enable_routes: false
    enable_virtualmachines: false
    container_platform: openshift
    ansible_operator_meta:
      namespace: fossul

  tasks:
  - name: Create fossul namespace
    k8s:
      name: fossul
      api_version: v1
      kind: Namespace
      state: present
  - import_role:
      name: fossul

